services:
  api:
    container_name: sauron
    image: saurondev/sauron:latest
    build: .
    # logging:
      # driver: fluentd
      # options:
        # fluentd-address: tcp://159.69.8.92:24224
        # tag: test.app
    ports:
      - "8084:8084"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
    networks:
      - sauron-network

networks:
  sauron-network:
    driver: bridge

volumes:
  data:
