services:
  api:
    container_name: sauron
    image: saurondev/sauron:latest
    build: .
    # logging:
      # driver: fluentd
      # options:
        # fluentd-address: tcp://159.69.8.92:24224
        # tag: test.app
    ports:
      - "8084:8084"
    volumes:
      - ./data:/app/data
      - ./migrations:/app/migrations
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://sauron:sauron@db:5432/sauron
    networks:
      - sauron-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: sauron
      POSTGRES_PASSWORD: sauron
      POSTGRES_DB: sauron
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - sauron-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sauron"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  sauron-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  data:
