services:
  api:
    container_name: sauron
    image: saurondev/sauron:latest
    build: .
    # logging:
      # driver: fluentd
      # options:
        # fluentd-address: tcp://159.69.8.92:24224
        # tag: test.app
    ports:
      - "8084:8084"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://sauron:sauron@db:5432/sauron
    networks:
      - sauron-network
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: sauron
      POSTGRES_PASSWORD: sauron
      POSTGRES_DB: sauron
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sauron-network

networks:
  sauron-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  data:
