services:
  api:
    container_name: sauron
    image: saurondev/sauron:latest
    build: .
    # logging:
      # driver: fluentd
      # options:
        # fluentd-address: tcp://159.69.8.92:24224
        # tag: test.app
    ports:
      - "8084:8084"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
    networks:
      - sauron-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      -"9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
    - sauron-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
    - prometheus
    networks:
    - sauron-network

networks:
  sauron-network:
    driver: bridge

volumes:
  data:
  grafana-data:
