name: Continous Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-build-push:
    # if: startsWith(github.ref, 'refs/tags/') && github.base_ref == 'main'
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            saurondev/sauron
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

# this is propapbly overkill
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image with Both Tags
        uses: docker/build-push-action@v6
        with:
          context: ./rust_rewrite
          file: ./rust_rewrite/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            saurondev/sauron:latest
          labels: ${{ steps.meta.outputs.labels }}


  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          key: ${{ secrets.SSH_KEY }}
          if_key_exists: fail # replace / ignore / fail

      - name: Copy docker-compose.yml to server
        run: |
          scp ./rust_rewrite/docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:~/sauron_docker
  
      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} '
            cd ~/sauron_docker
            sudo docker compose pull
            sudo docker compose up -d
          '
