on: push
name: Code Quality Checks

permissions:
  contents: read
  security-events: write

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Clippy
        run: |
          cd rust_rewrite
          cargo clippy --all-targets --all-features

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: rust_rewrite/Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          
      - name: Upload Hadolint results
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true