name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
           cd rust_rewrite/
           cargo build --verbose
    - name: Run tests
      run: |
           cd rust_rewrite/ 
           cargo test --verbose

  smoke-test:
    needs: build  # Ensures Rust completes first
    uses: ./.github/workflows/smoke_test.yml # Calls Smoke Test workflow