name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  security-events: write

jobs:
  build:

    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@v4

    - name: Cache Rust dependencies
      uses: useblacksmith/cache@v5
      with:
        path: |
          rust_rewrite/target
          ~/.cargo/registry
          ~/.cargo/git
        key: rust-${{ runner.os }}-${{ hashFiles('rust_rewrite/Cargo.lock') }}
        restore-keys: |
          rust-${{ runner.os }}-

    - name: Run Clippy
      run: |
        cd rust_rewrite
        cargo clippy --all-targets --all-features

    - name: Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: rust_rewrite/Dockerfile
        format: sarif
        output-file: hadolint-results.sarif
          
    - name: Upload Hadolint results
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: hadolint-results.sarif
        wait-for-processing: true

    - name: Build
      run: |
           cd rust_rewrite/
           cargo build --verbose
    - name: Run tests
      run: |
           cd rust_rewrite/ 
           cargo test --verbose