name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
           cd rust_rewrite/
           cargo build --verbose
    - name: Run tests
      run: |
           cd rust_rewrite/ 
           cargo test --verbose